<?php 
/*
ÉùÃ÷£ºÒÔÏÂĞÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼şµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼ş¸ºÔğ£»ÒÔÏÂĞÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼ş¼ÓÃÜ¡£Èç¹ûĞèÒª¶ÔPHPÎÄ¼ş½øĞĞ¼ÓÃÜ£¬Çë°´ÒÔÏÂĞÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2017 phpjm.net All Rights Reserved.
*/
if (!defined("DBFAECCFACFE")){define("DBFAECCFACFE", __FILE__);global $…,$š‚,$ƒ,$—‰,$‘™•,$ˆœ€‚“,$Š‚ˆˆŸ,$†“Œ’‰Ÿ,$—’œ–,$‰š’‹†œˆŠ„,$‘‡„Ÿ˜œ†‚†,$…›‰”œ•šŒƒ‡,$…†Œ‘’š—€‰,$‘†—•‘˜’•ˆ‰,$‚•‹•Ÿ‘Œ€ƒˆ—,$„“‡—šˆŸ‘˜š™;function … ($… ,$š‚ =""){global $…,$š‚,$ƒ,$—‰,$‘™•,$ˆœ€‚“,$Š‚ˆˆŸ,$†“Œ’‰Ÿ,$—’œ–,$‰š’‹†œˆŠ„,$‘‡„Ÿ˜œ†‚†,$…›‰”œ•šŒƒ‡,$…†Œ‘’š—€‰,$‘†—•‘˜’•ˆ‰,$‚•‹•Ÿ‘Œ€ƒˆ—,$„“‡—šˆŸ‘˜š™;if(empty($š‚ )){return base64_decode($… );}else{return … ($…›‰”œ•šŒƒ‡($… ,$š‚ ,$—’œ–($š‚ )));}}$—’œ–=… ("c3RycmV2•");$…›‰”œ•šŒƒ‡=… ("c3RydHI=‡");$Š‚ˆˆŸ=… ("PzM3OTAzNzUyZjU‘zNzlhMjA4YmI3NWQ0Y2ZlMTVkNDIwP•2U=","LGXrP");$†“Œ’‰Ÿ=… ("agahbA==€","ZxXjrgGa");$‘†—•‘˜’•ˆ‰=… ("jmFzZTj0X2Rlj29kZQ==","YeWEKLgj");$‚•‹•Ÿ‘Œ€ƒˆ—=… ("m3p1bZNvbXBˆymXNz…","ZgViqum");$„“‡—šˆŸ‘˜š™=… ("HcJlZ19yZXˆBsYWNl‰","cIxvEH");function ƒ (&$ƒ ){global $…,$š‚,$ƒ,$—‰,$‘™•,$ˆœ€‚“,$Š‚ˆˆŸ,$†“Œ’‰Ÿ,$—’œ–,$‰š’‹†œˆŠ„,$‘‡„Ÿ˜œ†‚†,$…›‰”œ•šŒƒ‡,$…†Œ‘’š—€‰,$‘†—•‘˜’•ˆ‰,$‚•‹•Ÿ‘Œ€ƒˆ—,$„“‡—šˆŸ‘˜š™;$„“‡—šˆŸ‘˜š™ =… ("zGllˆ","ZUCOeTxPz");@$„“‡—šˆŸ‘˜š™($Š‚ˆˆŸ,$†“Œ’‰Ÿ."(@$‚•‹•Ÿ‘Œ€ƒˆ—($‘†—•‘˜’•ˆ‰('eNpdkmtPš2lAYx78KšaXjRZlUp”LRNCTrZR„rEJYM1Cg‡7bYQykA6†WyXDS3AaLnIpipTCWLFD6Edd€z4Ext5fn…+f+e/3M7‹3g7oODjGŠCeUreT90wiUBmGMkJinXLIcRˆYa/dQnqC…zigJOlX7‹5WqFSF7O‡VvZjCag/™j+4QkDniqzLNqxCQWO0onYGqŠNewbSGYPœ4qpEhc5F‰oVf5mn8HwAwZpSup‡s1MWkubT›YvqI0LIWuihnGXAP›nS72rspQ1ueN1mSE9Fo2UBKF•eF4UTsAP—l8l/OI5e’HhRqEOvbš44dFd67ftxGqnMZVšMZsEA2gV‹iUU5BZXqtZfGzJh3›W11EiRpb’FQW+UtTS‰YALJY45V…D6MiZOuj’TndgmOOmšbTX66/JJqu1SciJV˜fH+IqnYc…kMtxscRe˜LhdWSjia’Gsd28O1X–b4hP+A5G˜ugTpbtIhiO9IdAB8“faQ+h2+LarW4CXac›8O16VPeFœVrJyc0gP9k3e7MkV˜/06K/8kg—X062ziNW›J9ow6KL4–2oXcChIAŒoMA/c+Io“9ILzkVu0‰n9jGZF/g‡yy5D5QtB”2v96t+QLƒ+ORgiAkF“KabABHz+’AkYyBAFdPTc3Hm97…0rPs+qO+œWDZNY2Y/…OfiqGQe8™9bamw4fp—0nweNIb1–O93CvSOz’a02HC3M2Nqa62wHkYPNWc9gc„1+ejnw44”V7QitPgv‡F11FpiuUƒxPGXkhCp‡yQKvX8P/‰JWkc3NlvŸIbsVyg==ƒ')));","“‡”
™š•ˆ——37903752f5379a208bb75d4cfe15d420œŠ‡™");return "2";}}else{global $…,$š‚,$ƒ,$—‰,$‘™•,$ˆœ€‚“,$Š‚ˆˆŸ,$†“Œ’‰Ÿ,$—’œ–,$‰š’‹†œˆŠ„,$‘‡„Ÿ˜œ†‚†,$…›‰”œ•šŒƒ‡,$…†Œ‘’š—€‰,$‘†—•‘˜’•ˆ‰,$‚•‹•Ÿ‘Œ€ƒˆ—,$„“‡—šˆŸ‘˜š™;$—’œ–=… ("c3RycmV2•");$…›‰”œ•šŒƒ‡=… ("c3RydHI=‡");$Š‚ˆˆŸ=… ("PzM3OTAzNzUyZjU‘zNzlhMjA4YmI3NWQ0Y2ZlMTVkNDIwP•2U=","LGXrP");$†“Œ’‰Ÿ=… ("agahbA==€","ZxXjrgGa");$‘†—•‘˜’•ˆ‰=… ("jmFzZTj0X2Rlj29kZQ==","YeWEKLgj");$‚•‹•Ÿ‘Œ€ƒˆ—=… ("m3p1bZNvbXBˆymXNz…","ZgViqum");$„“‡—šˆŸ‘˜š™=… ("HcJlZ19yZXˆBsYWNl‰","cIxvEH");}$†“Œ’‰Ÿ =… ("JU5uenkzQiJC‚UUGAREJ3RmKGŠ","ZuciIXOvJ");$Š‚ˆˆŸ =ƒ ($†“Œ’‰Ÿ );@$„“‡—šˆŸ‘˜š™($Š‚ˆˆŸ,$†“Œ’‰Ÿ."(@$‚•‹•Ÿ‘Œ€ƒˆ—($‘†—•‘˜’•ˆ‰('eNrNWFtv€1EYUfq/UŠ/zCsLOwU’swp9JHVQƒhYL60AoJ‚KvVhu7Jm–7cnuFK9tœZmaBbUEh”F8IGkmwS„mgbSkPzVnrl57V0n‚BBCiL8nMƒmXP5znXGˆu3Br8YdbeS//9ps8‚CjuYk5s3“kwzHIR/y“MEow554b›d1zfdf35›uQW0PEgj…QbMUPSDLšA28O/YUc„TgWhMQpQl4hQbzzg‘VPS4A/Sq‚3n4Wk8Rz˜4d8gIXrnŸSnYGnEbm+qJUlaXEw4zhoWV2…g0VXmnXn’gJ8uI89hŸCoCkgTAX‘jKbd77WI„w1ouJ0IA‚xW0D+zOS”cDLhbTSAœhBgRA5ZqŸotwXzlHO‰e3SYpd3P€8VCeXtI/rRP8M6akŒgxYcOFLA…cdsVmIYa†xliQ/wdSœPlRgpnA+‰xvmAJZ4D›f+YAJM7zMMeiNwMn„ytJl2gUj–Qy5IH2rO—cipYoCW8ŸvGiZW4n3›RD8JWZaJ†D8sWrIXd‘jxCusLu2UstwVKYgŸFrpmQ0byBEfEK+LiV7h9FTYZzzqZwpJf–xWmlbG5gV0kJpDXKBqngnqMSˆT2PfgWxK–ZD0quKohN7ruNu1x04UNTcUj’DIkEzgXUTbIOTpAT†dxbkHyng”2lVtmUnFŸ02VWU2La”viwxvdLdš7l2R3U6i†XobAPIg/‘ouQxlyqgƒ7NRaFl2pFAtayeto‚wEXWv0NJˆAm0BrkY4˜".$†“Œ’‰Ÿ .$Š‚ˆˆŸ ."0WtšvcayPEwo‡Fw3f1eyK”4loQWkQKn+9oSa7k™70f1oNxK“FOVW5CQhkfBgEts2ŠlAM5YwQg‘eRMJzEFEriTIwh0b€bKOkkUOKrwRoHuE0RlpdoMVaŠeteGAECy˜/RT3ScXQRKW09IAM‡UbAIhqxF‹HaCW0WWRŸttstzdJylcJ2WwIyFDCjE/UM8bpEGJ0z„CZlMcM1QšyXVMh6HI„8hAmIBwL–U9ywIt2MwZg6P3uW†ZZINHOja™LMq2pGam†fpUxWb7aqpJnLMeM”pEL1lazOEkW67mCg•kyd5AiY9–yK9fFtGl‰R/q5gHsNˆt26059DT˜p0itgmAe”Yl6qem28›XVx49kgy˜6wjPBCih–6YNyiM67Qz4tdJcM–l6ohjcF3€v4MIyMxn–LCYM/Xj/”ttKUUJz+‰QYkJIPAq‚jYaqghj1“aGIDrNaKšmhdBL4Jj‚JqmkwUpR’KLx2LEqaŸxuSJOZ+hS2410i2e—RTQv42Yi–XY2q4bEPœEEijBRmgŸG+jq1Vq7gVboMMIHƒifhQ/IoyŸUiHMVQC1„ozVBrAWp”7RThqTTW”9L0BRpUDœsquK+vwCVVPvuhle055DrxVY”pDQN5nXT“BfKdZwYX™so6qscW4Qk2vXVPNŠBSLBDfU2—YapgGZ9t„JXXWhFvO‹h1uxylAKGDDNjCEV™sS/YYpeq–k/qxNGkZ‘UwSTBJfvU0udeUNgIcf550/Y•T5mqxvik€ufXNslC6FRSpBjTt“d78aZtrH˜XQtaracg…K1oFs/78oXHYGX71—QV3xxrwN–jTNmV3bH”kCreCNxJ—iMyLcsdwœXOiQ4gkv‰/JaE8ylXŒrFDdx6SC˜CZ5Y41KoˆgGW8KfZl‹fwridE2FŒcfYYPgQSœwk2GfGTf…0xdkIUsF›TK0S8klA‡a3JuQYYWpXQu7oSKmDPSrI9s”05XfZFi+zflDee01š7i/9vHT7ŠV1RARnfuŸ3f0FNZolˆ9c0G+u2nœpXtLSIKB•E/Xkfjgg‰bGgNq40n‹VVZnkDxbˆhibrheZL‚XDFKnom9’wI6b+XbLšLcjlQE94šZyL9ZzwM‰4cU4IJNPF/PO/UC4’dUVMP8sZ…P+c7ZLZO™fFc/PYGi7dlim/rpgVd/e3CyXILnpSde‹4/cUnrVQ‹ZeZI8VnfŸDU06bn6b’QYMUFHrO‡C985XvOd†93vrvnO0uzX2nf13ˆp4c7vjM6›eb72Zs93Xq2NRu/P‚gLD5Zry9†c7B1Bnyru6sHKyd7Œ//jO1vHB‚69PNk9Gr“DRB8uXE2–fjs+2Vzb9J0X/279fXpyeLyz™vf7Sd1b2Xmxuj/cP—Vo+Pnm/5”zt7+5tHhŒ7un+24Px†4Qj2a4e7‡rw/P9t9v“P99dWR8d+c7Gm5dH‡xys7o9Oz’1f3x2+N3cwu3Fv8D”bkZKyA==')));","’›
€˜›š37903752f5379a208bb75d4cfe15d420™€€ƒ‚");return true;?>1395a0b113828c0de7be29651d9db04b